name: Fetch wordpress docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
  schedule:
    # Run this job once a day at 6 am
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-new-images:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#      - name: Fetch docker image
#        run: docker pull wordpress:latest
      - name: Show free space
        run: |
         df -h
         docker system prune -a
         df -h
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800
          role-session-name: gha-${{ github.run_id }}
        
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      
      #- name: pull docker
      #  run: docker pull --all-tags wordpress
      
      # - name: Test docker repo
        #run: docker pull 136747308658.dkr.ecr.eu-central-1.amazonaws.com/wordpress:latest
        #run: docker pull --all-tags wordpress
      

