name: Test release

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-opa:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: STS
        run: aws sts get-caller-identity