name: Test release

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    uses: ./.github/main-workflow.yml
    with:
      demo-value: fabian