name: Children Workflow

on:
  workflow_dispatch:
    inputs:
      MODE:
        description: 'plan or apply stages'
        default: 'plan'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-in-cw:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps: 
      - name: Print Mode
        run: |
          echo "The selected mode is: ${{ github.event.inputs.MODE }}"
