# name: Close Pull Request

# on:
#   pull_request_target:
#     types:
#       - opened
#     branches:
#       - main

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: superbrothers/close-pull-request@v3
#       with:
#         # Optional. Post a issue comment just before closing a pull request.
#         comment: "PRs targeting main branch are not allowed. Do not use GitHub's merge feature. Rebase locally instead. #testmarkdown ##test2 "
