name: Test release

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Print branch name
        run: |
          echo "1 Branch is" : ${{ github.ref_name }}
