name: Test release

on:
  workflow_call:
    inputs:
      demo-value:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: this-repository

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.3

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
