name: Test release

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: this-repository

      - name: Checkout datadrivers/github-actions-environment
        uses: actions/checkout@v3
        with:
          repository: datadrivers/github-actions-environment
          path: virtual-environments
          ref: v0.0.2
      
      - name: ls
        run:
          ls
