on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        run:  echo "CHANGELOG=$(git log --oneline )" >> $GITHUB_ENV # echo "CHANGELOG=$(git log --oneline | grep ci )" >> $GITHUB_ENV

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "foobar-4.3.1"
          # git log --oneline | grep ci 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: foobar-4.3.1
          body: Newly added changes ${{ env.CHANGELOG }} # ${{ github.run_id }}
          files: |
            CHANGELOG.md