on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_VERSION from git tag as ENV
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV