name: Create GitHub Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create GitHub release tag
        run: |
          git tag 14.0.0
          git push origin 14.0.0
